### PR TITLE
fix: `nowdoc/heredoc` newline

### LINKED ISSUE #618: broken echo output with heredoc/nowdoc
Input:
```php
echo <<<END
This uses the "here document" syntax to output
multiple lines with $variable interpolation. Note
that the here document terminator must appear on a
line with just a semicolon. no extra whitespace!
END
,
    'test';
```

Output:
```php
echo <<<END
This uses the "here document" syntax to output
multiple lines with $variable interpolation. Note
that the here document terminator must appear on a
line with just a semicolon. no extra whitespace!
END,
    'test';
```

`,` should be on next line

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #618

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -241,7 +241,36 @@ function isFirstChildrenInlineNode(path) {
...
+
+  if (parent.kind === "parameter") {
+    const parentParent = path.getParentNode(1);
+    const lastIndex = parentParent.arguments.length - 1;
+    const index = parentParent.arguments.indexOf(parent);
+
+    return index !== lastIndex;
+  }
+
+  return false;
```
Comment (evilebottnawi) [inline src/util.js]: Avoid extra newline if `nowdoc/heredoc` is last
