### PR TITLE
fix: compatibility with prettier 2.0

### LINKED ISSUE #1352: Unable to use plugin with Prettier 2.0 (TypeError: locEnd is not a function)
**Prettier 2.0.1**

**PHP Plugin 0.13.0**

Just happen to have bad timing on my part and was troubleshooting getting the plugin working. In the end i realized that a new version of Prettier was just published and it seems to break this plugin. I didn't see another issue open for this so i hope this isn't a dupe. 

## Error
```
yarn prettier tests/Feature/ExampleTest.php --check 
yarn run v1.22.4
$ prettier tests/Feature/ExampleTest.php --check
Checking formatting...
tests/Feature/ExampleTest.php[error] tests/Feature/ExampleTest.php: TypeError: locEnd is not a function
[error]     at getNextNonSpaceNonCommentCharacterIndex (/Users/jeffbeltran/code/foo/node_modules/prettier/index.js:12223:70)
[error]     at handleLastFunctionArgComments (/Users/jeffbeltran/code/foo/node_modules/@prettier/plugin-php/src/comments.js:285:25)
[error]     at handleOwnLineComment (/Users/jeffbeltran/code/foo/node_modules/@prettier/plugin-php/src/comments.js:45:5)
[error]     at /Users/jeffbeltran/code/foo/node_modules/prettier/bin-prettier.js:13942:11
[error]     at Array.forEach (<anonymous>)
[error]     at Object.attach (/Users/jeffbeltran/code/foo/node_modules/prettier/bin-prettier.js:13913:12)
[error]     at attachComments (/Users/jeffbeltran/code/foo/node_modules/prettier/bin-prettier.js:14771:14)
[error]     at coreFormat (/Users/jeffbeltran/code/foo/node_modules/prettier/bin-prettier.js:14802:23)
[error]     at format (/Users/jeffbeltran/code/foo/node_modules/prettier/bin-prettier.js:15024:75)
[error]     at formatWithCursor (/Users/jeffbeltran/code/foo/node_modules/prettier/bin-prettier.js:15040:12)
All matched files use Prettier code style!
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Fix
downgrading to 1.19.1 fixes this error.

### PR DESCRIPTION
**Pull request by czosel**
Prettier 2.0 brought some breaking changes with it ([see here](https://prettier.io/blog/2020/03/21/2.0.0.html#plugin-api-changes-in-prettierutil-6993httpsgithubcomprettierprettierpull6993-by-fiskerhttpsgithubcomfisker)). This implements the new API in a backwards-compatible way. CI currently doesn't proof the fact that it still works with 1.x, and since the breaking changes are few and nicely encapsulated, I'd keep CI as is.

Fixes #1352

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -3,9 +3,38 @@
...
+  return _isNextLineEmpty(text, node, lookupIfPrettier2(options, "locEnd"));
+}
+
+function getNextNonSpaceNonCommentCharacterIndex(text, node, options) {
+  return _getNextNonSpaceNonCommentCharacterIndex(
+    text,
+    node,
+    lookupIfPrettier2(options, "locEnd")
+  );
+}
```
Comment (czosel) [inline src/util.js]: These are the actual code changes

(probably should've done a separate commit for the formatting changes :see_no_evil:)

**Comment by czosel** [comment]
You can try checking out this branch, and after run `yarn add prettier@1.19.1` and then `yarn test` - the only issue you should see are linting errors.

**Comment by evilebottnawi** [comment]
Great, go ahead

**Comment by matzeeable** [comment]
@czosel Awesome! When will this be published as new version to https://www.npmjs.com/package/@prettier/plugin-php ? 🙂

**Comment by czosel** [comment]
@matzeeable I hope we can make a release in the next few days, all that's missing are some reviews to open merge requests :slightly_smiling_face:
