### PR TITLE
fix: don't break assign with multiline

### LINKED ISSUE #461: Linebreak in multiline strings
Some multiline strings seem to have a linebreak before the opening quote. It seems to have something to do both with line length and number of lines :confused: 

Input:
```php
$multiline = '
  looooooooooooooooooooooooooooooooooooooooooooooooooooooong
  more
';
```
Output:
```php
$multiline =
     '
  looooooooooooooooooooooooooooooooooooooooooooooooooooooong
  more
';
```

Excpected output: Same as input.

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #461

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -1731,13 +1731,20 @@ function printStatement(path, options, print) {
         //     : false;
         (node.right.kind === "retif" && node.right.test.kind === "bin") ||
         isPropertyLookupChain(node.right);
+      const isMultiLineString =
+        node.right.kind === "string" && node.right.raw.indexOf("\n") !== -1;
```
Comment (czosel) [inline src/printer.js]: You can use `includes()` instead of `indexOf() !== -1`
