### PR TITLE
Retif comments support

### LINKED ISSUE #281: Comments in anonymous function inside ternary
Gotta love those edge cases:
```php
abstract class Kernel
{
    protected function initializeContainer()
    {
        $previousHandler = previousHandler ?: set_error_handler(function () {
            $foo = "bar";
            // Clean the trace by removing first frames added by the error handler itself.
        });
    }
}
```
`[error] ../symfony/src/Symfony/Component/HttpKernel/Kernel.php: Error: Comment "// Clean the trace by removing first frames added by the error handler itself." was not printed. Please report this error!`

### PR DESCRIPTION
**Pull request by czosel**
Fixes #281

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -134,6 +134,10 @@ const printers = {
         {
           kinds: ["parameter"],
           children: { listNodes: [], nodes: ["value"] }
+        },
+        {
+          kinds: ["retif"],
+          children: { listNodes: [], nodes: ["trueExpr", "falseExpr"] }
```
Comment (mgrip) [inline src/index.js]: should probably add [test](https://github.com/glayzzle/php-parser/blob/master/docs/AST.md#retif) as well

Comment (czosel) [reply src/index.js]: Good catch! done.
