### PR TITLE
Fix escaping in encapsed nodes

### LINKED ISSUE #298: Quote escaping removed
Input:
```php
$test = "\"$commandName\"";
```
Output:
```php
$test = ""$commandName"";
```

### PR DESCRIPTION
**Pull request by czosel**
Fixes #298

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -524,9 +524,7 @@ function printExpression(path, options, print) {
             path.map(valuePath => {
               const node = valuePath.getValue();
               if (node.kind === "string") {
-                return valuePath.getParentNode().type === "heredoc"
```
Comment (mgrip) [inline src/printer.js]: you can probably get rid of some extra logic under "string" now that we aren't printing this

Comment (czosel) [reply src/printer.js]: Good catch! Please check again 😄

**Comment by mgrip** [comment]
🎉
